import { Router } from 'express';
import { videoProjectController } from '../../controllers/video-project.controller';
import { authenticate } from '../../middleware/auth.middleware';

const router = Router();
router.use(authenticate);
router.post('/:bookId/video-projects', videoProjectController.create);
router.get('/:bookId/video-projects', videoProjectController.list);
router.get('/video-projects/:projectId', videoProjectController.get);
router.get('/video-projects/:projectId/progress', videoProjectController.progress);
router.post('/video-projects/:projectId/analyze', videoProjectController.analyze);
router.post('/video-projects/:projectId/plan', videoProjectController.plan);
router.post('/video-projects/:projectId/generate', videoProjectController.generate);
router.post('/video-projects/:projectId/pause', videoProjectController.pause);
router.post('/video-projects/:projectId/resume', videoProjectController.resume);
router.post('/video-projects/:projectId/cancel', videoProjectController.cancel);
router.post('/video-projects/:projectId/render', videoProjectController.render);
router.post('/video-projects/:projectId/subtitles', videoProjectController.generateSubtitles);
router.patch('/video-projects/:projectId/subtitle-settings', videoProjectController.updateSubtitleSettings);
router.get('/video-projects/:projectId/scenes', videoProjectController.listScenes);
router.get('/video-scenes/:sceneId', videoProjectController.getScene);
router.post('/video-scenes/:sceneId/regenerate', videoProjectController.regenerateScene);
router.post('/video-scenes/:sceneId/generate', videoProjectController.regenerateScene);
router.patch('/video-scenes/:sceneId/prompt', videoProjectController.updateScenePrompt);
router.patch('/video-shots/:shotId/prompt', videoProjectController.updateShotPrompt);
router.post('/video-shots/:shotId/regenerate', videoProjectController.regenerateShot);
router.post('/video-shots/:shotId/generate-camera', videoProjectController.generateCameraForShot);
router.post('/video-shots/:shotId/fix-continuity', videoProjectController.fixCameraContinuity);
export default router;
