
-- Align focus / DOF / angle enums; add focusTarget
ALTER TYPE "FocusMode" ADD VALUE IF NOT EXISTS 'SHALLOW_FOCUS';
ALTER TYPE "FocusMode" ADD VALUE IF NOT EXISTS 'AUTO_FOCUS';
ALTER TYPE "FocusMode" ADD VALUE IF NOT EXISTS 'SELECTIVE_FOCUS';
ALTER TYPE "DepthOfField" ADD VALUE IF NOT EXISTS 'MODERATE';
ALTER TYPE "DepthOfField" ADD VALUE IF NOT EXISTS 'EXTREME_SHALLOW';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'OVER_SHOULDER';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'TOP_DOWN';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'BOTTOM_UP';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'POV';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'PROFILE';
ALTER TYPE "CameraAngle" ADD VALUE IF NOT EXISTS 'THREE_QUARTER';
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "focusTarget" TEXT;
