export const PLANS = [
  {
    id: "FREE",
    name: "Free",
    price: 0,
    description: "Get started and explore the platform",
    features: [
      "1 book",
      "1 audience audit / month",
      "5 AI creatives / month",
      "Basic analytics",
    ],
    cta: "Start free",
    popular: false,
  },
  {
    id: "STARTER",
    name: "Starter",
    price: 29,
    description: "For authors launching their first campaigns",
    features: [
      "3 books",
      "5 audience audits / month",
      "50 AI creatives / month",
      "30-day marketing calendar",
      "Email & TikTok creatives",
      "Email support",
    ],
    cta: "Start Starter",
    popular: false,
  },
  {
    id: "PRO",
    name: "Pro",
    price: 79,
    description: "Full marketing OS for serious authors",
    features: [
      "Unlimited books",
      "Unlimited audience audits",
      "Unlimited AI creatives",
      "Auto campaign optimization",
      "Amazon keyword ads",
      "A/B testing",
      "Priority support",
      "Export reports",
    ],
    cta: "Go Pro",
    popular: true,
  },
  {
    id: "AGENCY",
    name: "Agency",
    price: 199,
    description: "For teams and author service businesses",
    features: [
      "Everything in Pro",
      "Multi-user seats",
      "White-label reports",
      "API access",
      "Dedicated success manager",
      "Custom integrations",
    ],
    cta: "Contact sales",
    popular: false,
  },
] as const;
