export const ROUTES = {
  home: "/",
  features: "/features",
  pricing: "/pricing",
  about: "/about",
  blog: "/blog",
  contact: "/contact",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  books: "/books",
  booksNew: "/books/new",
  auditNew: "/audit/new",
  creatives: "/creatives",
  calendar: "/calendar",
  analytics: "/analytics",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsBilling: "/settings/billing",
  settingsApiKeys: "/settings/api-keys",
  settingsNotifications: "/settings/notifications",
} as const;
