-- Cinematic camera movement system (first-class VideoShot fields)
DO $$ BEGIN CREATE TYPE "CameraMovement" AS ENUM (
  'STATIC','PAN_LEFT','PAN_RIGHT','TILT_UP','TILT_DOWN','DOLLY_IN','DOLLY_OUT','PUSH_IN','PULL_OUT',
  'TRACKING','FOLLOW','ORBIT','ARC','CRANE_UP','CRANE_DOWN','BOOM_UP','BOOM_DOWN','HANDHELD','STEADICAM',
  'GIMBAL','ZOOM_IN','ZOOM_OUT','WHIP_PAN','DRONE_RISE','DRONE_DESCEND','DRONE_FORWARD','DRONE_BACKWARD',
  'DOLLY_ZOOM','POV','FIRST_PERSON','CUSTOM'
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "CameraSpeed" AS ENUM ('VERY_SLOW','SLOW','MEDIUM','FAST','VERY_FAST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "CameraRig" AS ENUM (
  'STATIC_TRIPOD','HANDHELD','STEADICAM','GIMBAL','DOLLY','CRANE','JIB','DRONE','SHOULDER','POV','UNKNOWN'
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "CameraAngle" AS ENUM (
  'EYE_LEVEL','LOW_ANGLE','HIGH_ANGLE','BIRDS_EYE','WORMS_EYE','DUTCH_ANGLE','OVERHEAD','GROUND_LEVEL'
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "CameraFraming" AS ENUM (
  'EXTREME_WIDE','WIDE','FULL','MEDIUM_WIDE','MEDIUM','MEDIUM_CLOSE_UP','CLOSE_UP','EXTREME_CLOSE_UP',
  'TWO_SHOT','OVER_SHOULDER','INSERT','CUTAWAY','POV_FRAME'
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "FocusMode" AS ENUM ('FIXED','RACK_FOCUS','FOLLOW_FOCUS','DEEP_FOCUS','SOFT_FOCUS');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "DepthOfField" AS ENUM ('SHALLOW','MEDIUM','DEEP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE "MovementPurpose" AS ENUM (
  'ESTABLISH_LOCATION','FOLLOW_CHARACTER','FOLLOW_ACTION','BUILD_TENSION','CREATE_INTIMACY','CREATE_DISTANCE',
  'SHOW_SCALE','REVEAL_INFORMATION','REVEAL_CHARACTER','REVEAL_OBJECT','EMPHASIZE_EMOTION','CREATE_DISORIENTATION','TRANSITION'
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "cameraMovement" "CameraMovement";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "cameraSpeed" "CameraSpeed";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "cameraDirection" TEXT;
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "cameraAngle" "CameraAngle";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "cameraRig" "CameraRig";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "focalLength" TEXT;
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "framing" "CameraFraming";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "focusMode" "FocusMode";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "depthOfField" "DepthOfField";
ALTER TABLE "video_shots" ADD COLUMN IF NOT EXISTS "movementPurpose" "MovementPurpose";

CREATE INDEX IF NOT EXISTS "video_shots_cameraMovement_idx" ON "video_shots"("cameraMovement");
